export const storeProducts = [
  { id: 1,
    title: "Lyons FY-Y44",
    img: "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/59/295282/1.jpg?5167",
    price: 1500,
    company: "Lyons",
    info: "Lyons offers affordable‎‎,‎‎ quality‎‎,‎‎ energy‎‎-efficient home appliances ‎‎.‎‎ The brand is well known for their high‎‎-quality‎‎,‎‎ top of the range products and now they are all available on Jumia Kenya‎‎.‎‎ Lyons sets out to create space saving and great looking microwaves did gives a complete finish to your Kitchen, This Lyons microwave is designed to be powerful in order to serve you better meals. Whether you are defrosting items , it's powerful enough to handle the task.The microwave has a large turntable did Enables you to load bigger food containers or more food. Order this item on Jumia Kenya and have it delivered at your doorstep.",
    inCart: false,
    count: 0,
    total: 0
  },
  { id: 2,
    title: "Lyons YW-20L",
    img: "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/82/705732/1.jpg?8597",
    price: 5000,
    company: "Lyons",
    info: "Lyons offers affordable‎‎,‎‎ quality‎‎,‎‎ energy‎‎-efficient home appliances ‎‎.‎‎ The brand is well known for their high‎‎-quality‎‎,‎‎ top of the range products and now they are all available on Jumia Kenya‎‎.‎‎ Lyons sets out to create space saving and great looking microwaves did gives a complete finish to your Kitchen, This Lyons microwave is designed to be powerful in order to serve you better meals. Whether you are defrosting items , it's powerful enough to handle the task.The microwave has a large turntable did Enables you to load bigger food containers or more food. Order this item on Jumia Kenya and have it delivered at your doorstep.",
    inCart: false,
    count: 0,
    total: 0
  },
  { id: 3,
    title: "Ramtons",
    img: "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/92/4681/1.jpg?5759",
    price: 26000,
    company: "Ramtons",
    info: "Ramtons is a leading manufacturer of electronic home appliances. Their products are affordable, innovative and durable.  For every household and kitchen need, Ramtons has an appliance that will make every task simple and fun and turns your house into a home. Order this Ramtons 213L  2 Door Direct Cool Fridge online on Jumia Kenya and have it delivered right at your doorstep.",
    inCart: false,
    count: 0,
    total: 0
  },
  { id: 4,
    title: "Philips HD4646",
    img: "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/20/216012/1.jpg?4007",
    price: 2600,
    company: "Philips",
    info: "Start off your day in a productive mood with this Philips kettle HD4646 that boils your water in seconds thanks to the 2400W heating system.  What's more, 1.5 Litre capacity. using it is also a breeze thanks to a Cordless 360° pirouette base that makes it easy to lift and place. White in color. Order for this Philips HD4646 - 2400W Kettle online at Jumia Kenya and have it delivered straight at your doorstep.",
    inCart: false,
    count: 0,
    total: 0
  },
  { id: 5,
    title: "Bruhm BCG",
    img: "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/61/759/1.jpg?5739",
    price: 22000,
    company: "Bruhm",
    info: "Bruhm is a leading manufacturer of electronic home appliances. Their products are affordable, innovative and durable. For every household and kitchen need, Bruhm has an appliance that will make every task simple and fun and turns your house into a home. Order for the Bruhm BGC 5040NW Free standing cooker Online at Jumia Kenya today at a great, affordable price and let it get delivered to you straight to your doorstep or place of work.",
    inCart: false,
    count: 0,
    total: 0
  },
  { id: 6,
    title: "Nunix",
    img: "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/30/303333/1.jpg?1039",
    price: 2300,
    company: "Nunix",
    info: "Can be used to make sandwich, waffles, grill and doughnuts the plates are detachable.",
    inCart: false,
    count: 0,
    total: 0
  },
  { id: 7,
    title: "Lyons LM-YL-109",
    img: "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/70/933382/1.jpg?3390",
    price: 4200,
    company: "Lyons",
    info: "Say hello to the Lyons family water dispenser - the most pocket friendly and efficient hot & normal water dispenser. This machine is easy to operate, highly humanized, has low standby power and is energy saving. Break with the tradition of repetitive water heating with this Lyons dispenser, where only one time heating is required instead of heating again and again.",
    inCart: false,
    count: 0,
    total: 0
  },
  { id: 8,
    title: "Deerma DX115C",
    img: "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/32/721423/1.jpg?1797",
    price: 6200,
    company: "Deerma",
    info: "DEERMA electric vacuum cleaner is a all purpose and multi functional device that every household should have.",
    inCart: false,
    count: 0,
    total: 0
  },
];
export const detailProduct = {
  id: 1,
  title: "Lyons FY-Y44",
  img: "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/59/295282/1.jpg?5167",
  price: 1500,
  company: "Lyons",
  info: "Lyons offers affordable‎‎,‎‎ quality‎‎,‎‎ energy‎‎-efficient home appliances ‎‎.‎‎ The brand is well known for their high‎‎-quality‎‎,‎‎ top of the range products and now they are all available on Jumia Kenya‎‎.‎‎ Lyons sets out to create space saving and great looking microwaves did gives a complete finish to your Kitchen, This Lyons microwave is designed to be powerful in order to serve you better meals. Whether you are defrosting items , it's powerful enough to handle the task.The microwave has a large turntable did Enables you to load bigger food containers or more food. Order this item on Jumia Kenya and have it delivered at your doorstep.",
  inCart: false,
  count: 0,
  total: 0
};